#!/usr/bin/env bash
# ============================================================
# Pixel Verification Bot - Ubuntu/EC2 installer
#
# Usage:
#   bash setup.sh
#   bash setup.sh --bot-token "123:abc" --admin-id "123456789"
#   BOT_TOKEN="123:abc" ADMIN_ID="123456789" bash setup.sh
#
# If you run it through sudo, keep env vars with:
#   sudo BOT_TOKEN="123:abc" ADMIN_ID="123456789" bash setup.sh
# ============================================================

set -Eeuo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log() { echo -e "${CYAN}[setup]${NC} $*"; }
ok() { echo -e "${GREEN}[ok]${NC} $*"; }
warn() { echo -e "${YELLOW}[warn]${NC} $*"; }
fail() { echo -e "${RED}[error]${NC} $*" >&2; exit 1; }

usage() {
    cat <<'EOF'
Pixel Verification Bot installer

Options:
  --bot-token TOKEN     Telegram bot token from @BotFather
  --admin-id ID         Telegram admin user ID
  --bot-dir DIR         Install/update directory (default: ~/pixel-bot)
  --service NAME        systemd service name (default: pixel-bot)
  --non-interactive     Do not prompt; fail if required values are missing
  -h, --help            Show this help

Examples:
  bash setup.sh
  bash setup.sh --bot-token "123:abc" --admin-id "123456789"
  sudo BOT_TOKEN="123:abc" ADMIN_ID="123456789" bash setup.sh
EOF
}

BOT_TOKEN="${BOT_TOKEN:-}"
ADMIN_ID="${ADMIN_ID:-}"
BOT_DIR="${BOT_DIR:-}"
SERVICE_NAME="${EC2_SERVICE:-pixel-bot}"
NON_INTERACTIVE=0

while [ "$#" -gt 0 ]; do
    case "$1" in
        --bot-token)
            [ "${2:-}" ] || fail "--bot-token requires a value"
            BOT_TOKEN="$2"
            shift 2
            ;;
        --admin-id)
            [ "${2:-}" ] || fail "--admin-id requires a value"
            ADMIN_ID="$2"
            shift 2
            ;;
        --bot-dir)
            [ "${2:-}" ] || fail "--bot-dir requires a value"
            BOT_DIR="$2"
            shift 2
            ;;
        --service)
            [ "${2:-}" ] || fail "--service requires a value"
            SERVICE_NAME="$2"
            shift 2
            ;;
        --non-interactive)
            NON_INTERACTIVE=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            fail "Unknown option: $1. Run: bash setup.sh --help"
            ;;
    esac
done

echo -e "${BOLD}"
echo "=================================================="
echo " Pixel Verification Bot - EC2 Installer"
echo "=================================================="
echo -e "${NC}"

if ! command -v sudo >/dev/null 2>&1; then
    fail "sudo is missing. Run as a user with sudo access, for example ubuntu."
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ "$(id -u)" = "0" ]; then
    if [ -n "${SUDO_USER:-}" ] && [ "$SUDO_USER" != "root" ]; then
        BOT_USER="$SUDO_USER"
        BOT_HOME="$(getent passwd "$BOT_USER" | cut -d: -f6)"
    else
        BOT_USER="root"
        BOT_HOME="/root"
        warn "Running as root. systemd service will run as root."
    fi
else
    BOT_USER="$USER"
    BOT_HOME="$HOME"
fi

BOT_DIR="${BOT_DIR:-$BOT_HOME/pixel-bot}"
ENV_FILE="$BOT_DIR/.env"

prompt_secret() {
    local var_name="$1"
    local label="$2"
    local current_value="${!var_name:-}"

    if [ -n "$current_value" ]; then
        return
    fi

    if [ -f "$ENV_FILE" ]; then
        current_value="$(grep -E "^${var_name}=" "$ENV_FILE" 2>/dev/null | tail -n 1 | cut -d= -f2- || true)"
        current_value="${current_value%\"}"
        current_value="${current_value#\"}"
        current_value="${current_value%\'}"
        current_value="${current_value#\'}"
        if [ -n "$current_value" ]; then
            printf -v "$var_name" '%s' "$current_value"
            return
        fi
    fi

    if [ "$NON_INTERACTIVE" = "1" ]; then
        fail "$var_name is required. Provide --$(echo "$var_name" | tr '[:upper:]_' '[:lower:]-') or set $var_name."
    fi

    read -r -p "$label: " current_value
    printf -v "$var_name" '%s' "$current_value"
}

escape_env_value() {
    printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

write_env_file() {
    local tmp_file
    tmp_file="$(mktemp)"

    cat > "$tmp_file" <<EOF
# Pixel Verification Bot runtime config
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
BOT_TOKEN="$(escape_env_value "$BOT_TOKEN")"
ADMIN_ID="$(escape_env_value "$ADMIN_ID")"

# Optional: comma-separated list if you want multiple admins
# ADMIN_IDS=123456789,987654321

# Optional manual top-up display
PAYMENT_EASYPAISA="${PAYMENT_EASYPAISA:-0300-XXXXXXX}"
PAYMENT_JAZZCASH="${PAYMENT_JAZZCASH:-0301-XXXXXXX}"
PAYMENT_ACCOUNT_NAME="${PAYMENT_ACCOUNT_NAME:-Pixel Verification}"
EOF

    install -m 600 "$tmp_file" "$ENV_FILE"
    rm -f "$tmp_file"
    if [ "$BOT_USER" != "root" ]; then
        sudo chown "$BOT_USER:$BOT_USER" "$ENV_FILE"
    fi
}

log "Installing/updating bot files in $BOT_DIR"
mkdir -p "$BOT_DIR"
if command -v rsync >/dev/null 2>&1; then
    rsync -a \
        --exclude '.git/' \
        --exclude '.github/' \
        --exclude 'scripts/' \
        --exclude '.gitignore' \
        --exclude '.env' \
        --exclude 'bot_data.db*' \
        --exclude 'venv/' \
        --exclude '.cache/' \
        --exclude '__pycache__/' \
        "$SCRIPT_DIR"/ "$BOT_DIR"/
else
    tmp_dir="$(mktemp -d)"
    cp -a "$SCRIPT_DIR"/. "$tmp_dir"/
    rm -f "$tmp_dir/.env" "$tmp_dir/.gitignore" "$tmp_dir"/bot_data.db*
    rm -rf "$tmp_dir/.git" "$tmp_dir/.github" "$tmp_dir/scripts" \
        "$tmp_dir/venv" "$tmp_dir/.cache" "$tmp_dir/__pycache__"
    cp -a "$tmp_dir"/. "$BOT_DIR"/
    rm -rf "$tmp_dir"
fi
if [ "$BOT_USER" != "root" ]; then
    sudo chown -R "$BOT_USER:$BOT_USER" "$BOT_DIR"
fi

prompt_secret BOT_TOKEN "Enter BOT_TOKEN from @BotFather"
prompt_secret ADMIN_ID "Enter ADMIN_ID from @userinfobot"

[ -n "$BOT_TOKEN" ] || fail "BOT_TOKEN is required."
[ -n "$ADMIN_ID" ] || fail "ADMIN_ID is required."
[[ "$ADMIN_ID" =~ ^[0-9]+$ ]] || fail "ADMIN_ID must be numeric."

write_env_file
ok "Wrote locked env file: $ENV_FILE"

log "Updating apt and installing base packages"
sudo env DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a apt-get update -qq
sudo env DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a apt-get install -y -qq \
    python3 python3-pip python3-venv \
    git screen curl ca-certificates
ok "Base packages installed"

cd "$BOT_DIR"

if [ ! -d venv ]; then
    log "Creating Python virtual environment"
    python3 -m venv venv
fi

# shellcheck disable=SC1091
source venv/bin/activate
pip install --upgrade pip -q
ok "Virtual environment ready"

log "Installing Python requirements"
RETRIES=3
for attempt in $(seq 1 "$RETRIES"); do
    if pip install -r requirements.txt -q; then
        ok "Python packages installed"
        break
    fi
    warn "pip install attempt $attempt failed"
    [ "$attempt" = "$RETRIES" ] && fail "pip install failed after $RETRIES attempts"
    sleep 3
done

export PLAYWRIGHT_BROWSERS_PATH="$BOT_DIR/.cache/ms-playwright"
mkdir -p "$PLAYWRIGHT_BROWSERS_PATH"
if [ "$BOT_USER" != "root" ]; then
    sudo chown -R "$BOT_USER:$BOT_USER" "$BOT_DIR/.cache"
fi

log "Installing Playwright system dependencies"
sudo env DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a \
    "$BOT_DIR/venv/bin/playwright" install-deps chromium >/dev/null
ok "Playwright system libs installed"

log "Downloading Playwright Chromium"
playwright install chromium >/dev/null
ok "Chromium ready"

SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
log "Writing systemd unit: $SERVICE_FILE"
sudo tee "$SERVICE_FILE" >/dev/null <<EOF
[Unit]
Description=Pixel Verification Telegram Bot
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$BOT_USER
WorkingDirectory=$BOT_DIR
EnvironmentFile=$ENV_FILE
Environment="PLAYWRIGHT_BROWSERS_PATH=$BOT_DIR/.cache/ms-playwright"
ExecStart=$BOT_DIR/venv/bin/python3 $BOT_DIR/main.py
Restart=always
RestartSec=10

# Hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=read-only
ReadWritePaths=$BOT_DIR

[Install]
WantedBy=multi-user.target
EOF
sudo chmod 644 "$SERVICE_FILE"

sudo systemctl daemon-reload
sudo systemctl enable "$SERVICE_NAME" >/dev/null 2>&1
sudo systemctl restart "$SERVICE_NAME"
sleep 3

if systemctl is-active --quiet "$SERVICE_NAME"; then
    ok "Service '$SERVICE_NAME' is running"
else
    sudo systemctl status "$SERVICE_NAME" --no-pager || true
    fail "Service failed to start. Check logs with: journalctl -u $SERVICE_NAME -n 80 --no-pager"
fi

echo ""
echo -e "${GREEN}${BOLD}Deployment complete.${NC}"
echo ""
echo "Useful commands:"
echo "  sudo systemctl status $SERVICE_NAME"
echo "  sudo systemctl restart $SERVICE_NAME"
echo "  journalctl -u $SERVICE_NAME -f"
echo ""
echo "Bot directory: $BOT_DIR"
echo "Env file:      $ENV_FILE"
